# Generated by Django 3.2.10 on 2022-07-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot_api', '0001_initial'),
    ]

    def load_stores(apps, schema_editor):
        Slots = apps.get_model("slot_api", "Slot")
        for i in range(1,101):
            Slots.objects.create(title=f"slot-{i}")

    
    def delete_stores(apps, schema_editor):
        Slots = apps.get_model("slot_api", "Slot")
        Slots.objects.all().delete()


    operations = [migrations.RunPython(load_stores, delete_stores),]
    