# Generated by Django 3.2.10 on 2022-07-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_api', '0002_add_slot_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('vaccant', 'Vaccant')], default='available', max_length=10),
        ),
    ]
