# Generated by Django 3.2.10 on 2022-07-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slot_api', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='parkings',
        ),
        migrations.AddField(
            model_name='booking',
            name='bookings',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='slot_api.slot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='car_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
