# Generated by Django 3.2.10 on 2022-07-19 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slot_api', '0005_auto_20220717_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookings',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='parkings',
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='slot_api.slot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='account.profile'),
            preserve_default=False,
        ),
    ]
