# Generated by Django 3.2.10 on 2022-07-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_api', '0007_auto_20220722_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('vaccant', 'Vaccant')], default='occupied', max_length=10),
        ),
    ]
